export const regions = [
  "nacional",
  "internacional",
  "amazonas",
  "anzoátegui",
  "apure",
  "aragua",
  "barinas",
  "bolívar",
  "carabobo",
  "cojedes",
  "delta Amacuro",
  "falcón",
  "guárico",
  "lara",
  "mérida",
  "miranda",
  "monagas",
  "nueva Esparta",
  "portuguesa",
  "sucre",
  "táchira",
  "trujillo",
  "vargas",
  "yaracuy",
  "zulia",
];

export const services = ["médico", "psicólogo", "asistencia legal"];
