const RECAPTCHA_SITE_KEY = import.meta.env.PUBLIC_RECAPTCHA_SITE_KEY;
const RECAPTCHA_SEACRET_KEY = import.meta.env.RECAPTCHA_SEACRET_KEY;
const SUPABASE_URL = import.meta.env.SUPABASE_URL
const SUPABASE_KEY = import.meta.env.SUPABASE_ANON_KEY
const SUPABASE_DONATIONS_BUCKET = import.meta.env.SUPABASE_DONATIONS_BUCKET

export {RECAPTCHA_SITE_KEY, RECAPTCHA_SEACRET_KEY, SUPABASE_URL, SUPABASE_KEY, SUPABASE_DONATIONS_BUCKET};