import {Contact, db} from 'astro:db';

// https://astro.build/db/seed
export default async function seed() {
    await db.insert(Contact).values([
        {
            id: 1,
            name: "pedro perez",
            type: "asesoría legal",
            description: "lorem ipsum dolor site amet",
            phone: 4249999999,
            region: "distrito capital",
            telegram: "estootro",
            instagram: "estootro",
            whatsapp: "estootro",
            twitter: "estootro",
        },
        {
            id: 2,
            name: "pedro perez",
            type: "asesoría legal",
            description: "lorem ipsum dolor site amet",
            phone: 4249999999,
            region: "táchira",
            telegram: "estootro",
            instagram: "estootro",
            whatsapp: "estootro",
            twitter: "estootro",
        },
        {
            id: 3,
            name: "pedro perez",
            type: "asesoría legal",
            description: "lorem ipsum dolor site amet",
            phone: 4249999999,
            region: "falcón",
            telegram: "estootro",
            instagram: "estootro",
            whatsapp: "estootro",
            twitter: "estootro",
        },
        {
            id: 4,
            name: "pedro perez",
            type: "médico",
            description: "lorem ipsum dolor site amet",
            phone: 4249999999,
            region: "distrito capital",
            telegram: "estootro",
            instagram: "estootro",
            whatsapp: "estootro",
            twitter: "estootro",
        },
        {
            id: 5,
            name: "pedro perez",
            type: "médico",
            description: "lorem ipsum dolor site amet",
            phone: 4249999999,
            region: "trujillo",
            telegram: "estootro",
            instagram: "estootro",
            whatsapp: "estootro",
            twitter: "estootro",
        },
        {
            id: 6,
            name: "pedro perez",
            type: "médico",
            description: "lorem ipsum dolor site amet",
            phone: 4249999999,
            region: "yaracuy",
            telegram: "estootro",
            instagram: "estootro",
            whatsapp: "estootro",
            twitter: "estootro",
        },
        {
            id: 7,
            name: "pedro perez",
            type: "médico",
            description: "lorem ipsum dolor site amet",
            phone: 4249999999,
            region: "Apure",
            telegram: "estootro",
            instagram: "estootro",
            whatsapp: "estootro",
            twitter: "estootro",
        },
    ])
}
